version: 1.0.1-ci{build}

pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

image: Visual Studio 2017

environment:
  NugetApiKey:
    secure: SCsk5PEaEapMuqNlMjyyE6VDV9hEsTQ20gmgb78mRzrkXM1WbO9Ls883RWr50gEz

build: off

test_script:
- ps: . .\build\Start-Build.ps1 -Task Deploy

skip_commits:
  message: /updated readme.*|update readme.*s/
